### PR TITLE
Implement AI chat endpoint

### PR DESCRIPTION
**Pull request by DavidMStraub**
This is a work in progress implementing an LLM-based AI chat assistant endpoint for Gramps Web, based on the RAG (retrieval augmented generation) technique.

Short summary of the architecture:

- `gramps_webapi.api.search.text_semantic` converts Gramps objects to text for semantic indexing
- v1.0 of [Sifts](https://github.com/DavidMStraub/sifts) is used for providing a search index for vector embeddings, enabling semantic search
  - The new semantic search index is managed via a `--semantic` switch on the CLI commands and a `semantic` boolean query argument on the index endpoints
  - Vector embeddings are computed purely locally via [Sentence Transformers](https://sbert.net/)
- A new `/api/chat/` endpoint
  - Conducts a semantic search on the query
  - Feeds the top 10 search results along with the query to a LLM
  - returns the response

Configuration options:

- `VECTOR_EMBEDDING_MODEL`: the sentence transformers model to use for vector embeddings. E.g. `intfloat/multilingual-e5-small`
- `LLM_BASE_URL`: base URL for `openai-python`. If empty, uses the OpenAI API; but can use any OpenAI compatible API, e.g. using [Ollama](https://ollama.com/blog/openai-compatibility) locally
- `LLM_MODEL`: the model to use for chat. E.g., `gpt-4o-mini` for OpenAI or `tinyllama` for Ollama.

Guiding principles

- Fully local if desired, optionally leveraging APIs
- Disabled by default (resource consumption, privacy concerns, ...)

What's missing?

- [x] documentation, obviously
- [x] more unit tests
- [x] optional quota system per tree
- [x] limiting chat endpoint to user groups?
- [x] I'm still working on the `text_semantic` module to complete it for all object types and tweak it to improve semantic search recall and precision, which currently is not as good as I would like
- [x] A config option to limi context length rather than retrieving a fixed number of objects
- ~Possibly a better way to handle long notes~
- [x] Adding a default embedding model to the default docker image

I also plan to

- write a blog post with details about the architecture
- submit a PR to the frontend repo with a chat UI very soon

Note that this is meant to be an initial implementation laying the foundations; this can be made more powerful later on by introducing function calling etc.

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Docs: https://github.com/gramps-project/gramps-web-docs/pull/18

**Comment by emyoulation** [comment]
> This is a work in progress implementing an LLM-based AI chat assistant endpoint for Gramps Web, based on the RAG (retrieval augmented generation) technique.

Please introduce acronyms.
"This is a work in progress implementing a Large Language Model (LLM) based artificial intelligence (AI) chat assistant endpoint for Gramps Web, utilizing the Retrieval-Augmented Generation (RAG) technique."

**Comment by DavidMStraub** [comment]
Almost done. Expect to finish in the next 7 days.

**Comment by DavidMStraub** [comment]
- [] Update API docs for `/metadata/`

**Pull request merged**
