### PR TITLE
Refactor registering endpoints

### PR DESCRIPTION
**Pull request by dsblank**
This PR is the first step in allowing the app to support selectable endpoints, for example, leaving out the openAI LLM requirements. Could also allow an endpoint plugin API.

The next step is to figure out how to configure for the server and frontend. Maybe a config, or environment variable?

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Let's please discuss such major architecture changes in an issue first. I'm not saying I'm opposed to this, but I don't want to merge something that's a first step before roughly thinking through the subsequent ones.

**Comment by DavidMStraub** [comment]
(It would also be good if we could postpone major refactoring in existing modules until https://github.com/gramps-project/gramps-web-api/issues/567 is done, otherwise it will lead to tedious merge conflicts.)

**Comment by dsblank** [comment]
I didn't mean for this to be considered for merging! Just some code for discussion.

Regarding adding type hints: I see that you haven't done api/__init__.py yet. I volunteer to do that (possibly on a refactored version). But I'll start a discussion first.

**Comment by dsblank** [comment]
Added a place for discussion here: #585

**Comment by DavidMStraub** [comment]
> I didn't mean for this to be considered for merging! Just some code for discussion.

Got it!

> Regarding adding type hints: I see that you haven't done api/__init__.py yet. I volunteer to do that (possibly on a refactored version). But I'll start a discussion first.

Any help on this PR is more than welcome! I will stop working on it for today in 5 minutes :laughing: If something is unclear or discussion needed, you can just add a comment to the PR thread. Thank you!

**Pull request closed without merging**
